name: CI

on: [push, pull_request]

jobs:
  deploy-production:
    env: 
      SSH_USER: dead_fairy
      SSH_HOST: 130.193.57.7
      SSH_PORT: 22
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to production stage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd /home/dead_fairy/raddisson-tg-app
            git fetch --all
            git reset --hard origin/main
            docker compose up --build --force-recreate -d --no-deps
            sudo docker image prune -f
            sudo docker container prune -f
